" Undo some annoying latex-suite mappings
call IMAP ('__', '__', "tex")
call IMAP ('()', '()', "tex")
call IMAP ('[]', '[]', "tex")
call IMAP ('{}', '{}', "tex")
call IMAP ('^^', '^^', "tex")
call IMAP ('$$', '$$', "tex")
call IMAP ('==', '==', "tex")
call IMAP ('~~', '~~', "tex")
call IMAP ('=~', '=~', "tex")
call IMAP ('::', '::', "tex")
call IMAP ('((', '((', "tex")
call IMAP ('[[', '[[', "tex")
call IMAP ('{{', '{{', "tex")
