#!/usr/bin/env bash
DOTFILES_REPO=https://github.com/RubenVerborgh/dotfiles.git
DOTFILES_PATH=~/bin/dotfiles

echo "Ensuring git is installed..."
if ! which git > /dev/null; then
  echo "Installing git..."
  sudo apt-get install -y git || exit 1
fi

echo "Checking if dotfiles are installed..."
if [ ! -d "$DOTFILES_PATH" ]; then
  echo "Installing dotfiles..."
  echo mkdir -p "$(dirname $DOTFILES_PATH)"
   GIT_TERMINAL_PROMPT=0 git clone --depth 1 $DOTFILES_REPO $DOTFILES_PATH || exit 1
fi

echo "Updating and installing dotfiles..."
pushd "$DOTFILES_PATH"
yes | ./install || exit 1
popd

echo "All done."
