" Enter vim mode
set nocompatible

" Load pathogen
runtime bundle/pathogen/autoload/pathogen.vim
call pathogen#infect()
call pathogen#helptags()

syntax enable                     " Turn on syntax highlighting.
filetype plugin indent on         " Turn on file type detection.

set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.

set linebreak                     " Only break at word boundaries
set display=lastline              " Always show the last line

set backspace=indent,eol,start    " Intuitive backspacing.

set hidden                        " Handle multiple buffers better.

set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.

set ignorecase                    " Case-insensitive searching,
set smartcase                     " but case-sensitive if expression contains a capital letter.

set ruler                         " Show cursor position.

set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.

set wrap                          " Turn on line wrapping.
set scrolloff=3                   " Show 3 lines of context around the cursor.

set notitle                       " Remove the terminal's title

set visualbell                    " No beeping.

set nobackup                      " Don't make a backup before overwriting a file.
set directory=/tmp,.              " Keep swap files in one location

set tabstop=2                     " Global tab width.
set shiftwidth=2                  " And again, related.
set expandtab                     " Use spaces instead of tabs
set smartindent                   " Automatic indentation

au BufRead * normal zR            " Open unfolded

set laststatus=2                  " Show the status line all the time
set statusline=[%n]\ %<%.99f\ %h%w%m%r%y%=%-16(\ %l,%c\ %)%P

set t_Co=256
colorscheme wombat256mod

" Move by visible lines, not by actual lines
:nnoremap j gj
:nnoremap k gk
:nnoremap <up> gk
:nnoremap <down> gj

" Toggle NERDTree with F2
map <F2> :NERDTreeToggle<CR>
" Clear search highlight with F10
map <F10> :nohl<CR>

autocmd FileType mkd,tex set spell             " Always spell check these files

set wildignore+=node_modules/**                " Don't search inside Node.js modules


""""""""""""""""""""""""""
" Vim-LaTeX configuration
""""""""""""""""""""""""""
let g:Tex_MultipleCompileFormats='pdf, aux'    " pdf and aux files need multiple compilations
set grepprg=grep\ -nH\ $*                      " Make grep always show file name for Latex-Suite
let g:tex_flavor='latex'                       " .tex files should be recognized as TeX

autocmd FileType tex setlocal indentexpr=      " Disable automated indentation
let g:Tex_AdvancedMath = 0                     " Disable advanced math functions

" Viewer synchronization settings
let g:Tex_CompileRule_pdf = 'pdflatex -interaction=nonstopmode --synctex=1 $*'
let g:Tex_ViewRule_pdf = 'Skim'
let g:Tex_ViewRule_pdf = 'skimdisplayline'
let g:Tex_TreatMacViewerAsUNIX = 1

" Ignore the following TeX warnings
let g:Tex_IgnoredWarnings =
\"Underfull\n".
\"Overfull\n".
\"specifier changed to\n".
\"You have requested\n".
\"Missing number, treated as zero.\n".
\"There were undefined references\n".
\"Citation %.%# undefined\n".
\"Marginpar on page %.%# moved.\n".
\"LaTeX Font Warning:"
let g:Tex_IgnoreLevel = 9
