" ----------------
" General settings
" ----------------

set nocompatible                  " Enter vim mode

set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.

set linebreak                     " Only break at word boundaries
set display=lastline              " Always show the last line

set backspace=indent,eol,start    " Intuitive backspacing.

set hidden                        " Handle multiple buffers better.

set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.
set wildignore+=node_modules/**   " Don't search inside Node.js modules

set ignorecase                    " Case-insensitive searching,
set smartcase                     " but case-sensitive if expression contains a capital letter.

set ruler                         " Show cursor position.

set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.

set wrap                          " Turn on line wrapping.
set scrolloff=3                   " Show 3 lines of context around the cursor.

set notitle                       " Remove the terminal's title

set visualbell                    " No beeping.

set nobackup                      " Don't make a backup before overwriting a file.
set directory=/tmp,.              " Keep swap files in one location

set tabstop=2                     " Global tab width.
set shiftwidth=2                  " And again, related.
set expandtab                     " Use spaces instead of tabs
set smartindent                   " Automatic indentation

au BufRead * normal zR            " Open unfolded

set laststatus=2                  " Show the status line all the time
set statusline=[%n]\ %<%.99f\ %h%w%m%r%y%=%-16(\ %l,%c\ %)%P

set mouse=a                       " Enable mouse in all modes

set spell                         " Always spell check

" Move by visible lines, not by actual lines
nnoremap k gk
nnoremap j gj
nnoremap <up> gk
nnoremap <down> gj

" Clear search highlight with F10
map <F10> :nohl<CR>

" Set convenient leader key alternative
nmap ù \


" ------------
" Load bundles
" ------------

" Bundle manager
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'gmarik/vundle'
filetype plugin indent on

" Color schemes
Bundle 'baeuml/summerfruit256.vim'
Bundle 'tomasr/molokai'
Bundle 'vim-scripts/wombat256.vim'
colorscheme molokai
set t_Co=256
syntax on

" Motions and operations
Bundle 'tpope/vim-repeat'
Bundle 'tpope/vim-commentary'
Bundle 'tpope/vim-surround'

" Git integration
Bundle 'tpope/vim-fugitive'

" File navigation
Bundle 'git://git.wincent.com/command-t.git'
Bundle 'scrooloose/nerdtree'
map <F2> :NERDTreeToggle<CR>

" File type support
Bundle 'groenewege/vim-less'
Bundle 'kchmck/vim-coffee-script'
Bundle 'othree/html5.vim'
Bundle 'plasticboy/vim-markdown'
Bundle 'vim-scripts/JSON.vim'

Bundle 'LaTeX-Box-Team/LaTeX-Box'
let g:LatexBox_latexmk_options="-synctex=1"
let g:LatexBox_ignore_warnings=
  \['Underfull',
  \ 'Overfull',
  \ 'specifier changed to',
  \ 'Token not allowed in a PDF string',
  \ 'Package glossaries Warning',
  \ 'Package natbib Warning: Empty `thebibliography',
  \ 'Marginpar on page',
  \ 'Package microtype Warning',
  \ 'Label(s) may have changed.',
  \ ]
map <silent> <Leader>ls :silent
    \ !/Applications/Skim.app/Contents/SharedSupport/displayline -r -b -g
		\ <C-R>=line('.')<CR> "<C-R>=LatexBox_GetOutputFile()<CR>" "%:p" <CR>

" Various utilities
Bundle 'bronson/vim-trailing-whitespace'
Bundle 'RubenVerborgh/RefreshBrowsers'
